/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/components/auth-provider";
import { Toaster } from "@/components/ui/toaster";
import SideBar from "@/components/side-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={cn("antialiased overflow-x-hidden", inter.className)}
    >
      <body
        suppressHydrationWarning={true}
        className={cn(
          "min-h-screen w-full overflow-x-hidden antialiased ",
          inter.className
        )}
      >
        <AuthProvider>
          <div className="w-full mx-auto h-screen">
            <Navbar />
            <main className="w-full">{children}</main>
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
